parameters:
  - name: pathPrefix
    type: string
    default: SourceBranch
    values:
      - SourceBranch # matches branch/PR ref
      - SourceVersion # matches commit SHA

variables:
  ${{ if eq( parameters.pathPrefix, 'SourceBranch' ) }}:
    deployBasePath: "pr-deploy-site/${{ variables['Build.SourceBranch'] }}"
  ${{ if eq( parameters.pathPrefix, 'SourceVersion' ) }}:
    deployBasePath: "pr-deploy-site/${{ variables['Build.SourceVersion'] }}"

  deployHost: 'fabricweb.z5.web.core.windows.net'

  azureSubscription: 'UI Fabric (bac044cf-49e1-4843-8dda-1ce9662606c8)'

  ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    targetBranch: 'origin/$(System.PullRequest.TargetBranch)'

  backfillProvider: 'azure-blob'
  backfillOptions: '{"connectionString":"$(BACKFILL_CONNECTION_STRING)", "container":"$(BACKFILL_CONTAINER)"}'
